---
- hosts: localhost
  connection: local
  remote_user: root

  tasks:

  - name: read vars
    include_vars: '{{ item }}'
    with_first_found:
      - files:
          # "ansible_distribution" may be: "Debian", "SLES", "Ubuntu", "CentOS"
          # "ansible_distribution_version" may be: "9.0", "12.2", "16.04", "7.3.1611"
          # "ansible_distribution_major_version" may be: "9", "12", 16.04"
          # "ansible_os_family" may be: "Debian", "RedHat", "Suse"
          # Upper/lower case is important
          - "{{ ansible_os_family }}.yml"

          - "default.yml"
        paths: "./Operatin_Systems/"

  # - name: Pros specific installation.
  #   include: Pros/Arm-tool-chain.yml
  #   include: Pros/Pros-cli.yml