---
- hosts: localhost
  connection: local
  vars:
      armToolChainUrlPart: "https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-"
      version: "gcc-arm-none-eabi-10-2020-q4-major"

  tasks:
  - name: "Ansible | Print a variable"
    debug:
      msg: "The operating system is {{ ansible_os_family }}"

  - name: Install OS dependencies.
    include: "{{ lookup('first_found', OperatingSystems) }}"
    vars:
      OperatingSystems:
        - Operating_Systems/{{ ansible_os_family }}.packagenames.yml
        - Operating_Systems/default.packagenames.yml

  - name: Install arm tool chain.
    include: Pros/Arm-tool-chain.yml

  - name: Install Pros-cli.
    include: Pros/Pros-cli.yml

  - name: Add user to serial group.
    include: "{{ lookup('first_found', OperatingSystems) }}"
    vars:
      OperatingSystems:
        - Operating_Systems/{{ ansible_os_family }}.serialGroup.yml
        - Operating_Systems/default.serialGroup.yml

  - name: Adding upload bash alias
    include: Pros/upload-alias.yml
    when: upload is defined